var dir_d44c64559bbebec7f509842c48db8b23 =
[
    [ "userspace", "dir_1548687d2fb8d7e65e42c0056e9b0964.html", "dir_1548687d2fb8d7e65e42c0056e9b0964" ],
    [ "console.h", "console_8h.html", "console_8h" ],
    [ "debug.h", "debug_8h.html", "debug_8h" ],
    [ "elf.h", "elf_8h.html", "elf_8h" ],
    [ "fpu.h", "fpu_8h.html", "fpu_8h" ],
    [ "icon.h", "icon_8h.html", "icon_8h" ],
    [ "idt.h", "idt_8h.html", "idt_8h" ],
    [ "keyboard.h", "include_2keyboard_8h.html", "include_2keyboard_8h" ],
    [ "main.h", "main_8h.html", "main_8h" ],
    [ "memory.h", "memory_8h.html", "memory_8h" ],
    [ "misc.h", "misc_8h.html", "misc_8h" ],
    [ "mouse.h", "mouse_8h.html", "mouse_8h" ],
    [ "multiboot.h", "multiboot_8h.html", "multiboot_8h" ],
    [ "print.h", "print_8h.html", "print_8h" ],
    [ "shell.h", "shell_8h.html", "shell_8h" ],
    [ "storabs.h", "storabs_8h.html", "storabs_8h" ],
    [ "string.h", "string_8h.html", "string_8h" ],
    [ "syscall.h", "syscall_8h.html", "syscall_8h" ],
    [ "task.h", "task_8h.html", "task_8h" ],
    [ "vfs.h", "vfs_8h.html", "vfs_8h" ],
    [ "vga.h", "vga_8h.html", "vga_8h" ],
    [ "video.h", "include_2video_8h.html", "include_2video_8h" ],
    [ "wbuiltin.h", "wbuiltin_8h.html", "wbuiltin_8h" ],
    [ "wcall.h", "wcall_8h.html", "wcall_8h" ],
    [ "widget.h", "widget_8h.html", "widget_8h" ],
    [ "window.h", "include_2window_8h.html", "include_2window_8h" ],
    [ "wterm.h", "wterm_8h.html", "wterm_8h" ]
];